on:
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pull-requests: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run e2e tests
        run: npm run test
        continue-on-error: true

      - name: Process Cypress Test Results
        uses: im-open/process-cypress-test-results@v3
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'cypress/results/mochawesome.json'
          report-name: 'Cypress E2E Test Results'
          create-status-check: false
          create-pr-comment: true
          update-comment-if-one-exists: true
